name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Install nightly
      run: |
        rustup update
    - name: Build
      run: cargo +stable build --verbose
    - name: Run tests
      run: cargo +stable test --verbose

